# Generated by Django 5.1.1 on 2024-10-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_remove_car_created_at"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="car_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
        ),
    ]
