# Generated by Django 5.1 on 2024-08-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
    ]
